[package]
name = "pared"
version = "0.1.0"
edition = "2021"

[features]
# default_featurs = ["std"]
std = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
